# Deploys a socket filter eBPF program that looks for http requests, records
# them, tracks the corresponding responses generated by the server and outputs
# number of exchanges, sources and latencies

# Test with multiple interleaving exchanges and long fragmented responses

from bottle import route, run, template

@route('/')
def index():
    # 100 bytes of lorem ipsum
    return '''Lorem ipsum dolor sit amet, consectetur adipiscing elit.
     Mauris ut quam nec dolor sagittis volutpat.'''

run(host='localhost', port=8080)
